name: prnu
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.7  #.12
  - pytorch  # =1.13.1
  - pytorch-cuda  # =11.7
  - torchvision  # =0.14.1
  - tensorflow=2.2.0
  - tensorflow-gpu=2.2.0
  - tensorflow-base=2.2.0
  - tensorflow-estimator=2.2.0
  - scikit-learn
  - matplotlib
  - opencv  # 4.5.3
  - scipy
  - pip
  - av
  - pip:
    - pyexiftool==0.4.11
    - tensorflow-addons==0.11.2
